# Generated by Django 4.0.3 on 2022-04-08 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidWorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('customer', 'customer'), ('maid', 'maid')], default='customer', max_length=30)),
                ('addhar', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('work_type', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaidWorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('maid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maid_work_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maid.maidworkdetails')),
            ],
        ),
        migrations.AddField(
            model_name='maidworkdetails',
            name='maid_user',
            field=models.ManyToManyField(through='maid.MaidWorkHistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
