# Generated by Django 4.0.3 on 2022-04-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0003_maidworkdetails_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maidworkdetails',
            name='customer_user',
        ),
    ]
