# Generated by Django 4.0.3 on 2022-04-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0004_remove_maidworkdetails_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maidworkhistory',
            name='maid_user',
        ),
        migrations.RemoveField(
            model_name='maidworkhistory',
            name='maid_work_detail',
        ),
        migrations.DeleteModel(
            name='MaidWorkDetails',
        ),
        migrations.DeleteModel(
            name='MaidWorkHistory',
        ),
    ]
