# Generated by Django 4.0.3 on 2022-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0006_maidworkdetails_maidworkhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidworkhistory',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
