# Generated by Django 4.0.3 on 2022-04-13 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maid', '0007_maidworkhistory_is_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_working', models.BooleanField(default=False)),
                ('maid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='maidworkhistory',
            name='maid_user',
        ),
        migrations.RemoveField(
            model_name='maidworkhistory',
            name='maid_work_detail',
        ),
        migrations.DeleteModel(
            name='MaidWorkDetails',
        ),
        migrations.DeleteModel(
            name='MaidWorkHistory',
        ),
    ]
