# Generated by Django 4.0.3 on 2022-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0008_maidassign_remove_maidworkhistory_maid_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidassign',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='maidassign',
            name='is_working',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
